# Application
spring.application.name=Assistente_Virtual_Jargos
spring.docker.compose.skip.in-tests=false


# JPA / Hibernate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
# Cria o banco automaticamente caso ele nao exista no Docker
spring.flyway.create-schemas=true


# Spring AI - OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.speech.options.model=tts-1
spring.ai.openai.audio.speech.options.voice=alloy
spring.ai.openai.audio.speech.options.response-format=mp3