spring.application.name=Assistente_Virtual_Jargos
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.speech.options.model=tts-1
spring.ai.openai.audio.speech.options.voice=alloy
spring.ai.openai.audio.speech.options.response-format=mp3